##################################
# System
set_property PACKAGE_PIN E10 [get_ports INIT_CLK_P]
set_property IOSTANDARD LVDS_25 [get_ports INIT_CLK_P]
create_clock -period 10.000 -name INIT_CLK_P [get_ports INIT_CLK_P]

set_property PACKAGE_PIN C12 [get_ports clk_p_sitcp]
set_property IOSTANDARD LVDS_25 [get_ports clk_p_sitcp]
create_clock -period 10.000 -name INIT_CLK_P [get_ports clk_p_sitcp]

set_property PACKAGE_PIN E10 [get_ports EXT_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports EXT_CLK]
create_clock -period 8.000 -name INIT_CLK_P [get_ports EXT_CLK]

# set_property PACKAGE_PIN C9 [get_ports RESET_IN]
# set_property IOSTANDARD LVCMOS25 [get_ports RESET_IN]
# set_property PULLDOWN true [get_ports RESET_IN]
##################################
# Debug
set_property PACKAGE_PIN E13 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[0]}]
set_property PACKAGE_PIN E12 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[1]}]
set_property PACKAGE_PIN C14 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[2]}]
set_property PACKAGE_PIN C13 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[3]}]
set_property PACKAGE_PIN B12 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[4]}]
set_property PACKAGE_PIN B11 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[5]}]

set_property PACKAGE_PIN  C9  [get_ports  "SW[0]" ];
set_property IOSTANDARD LVCMOS25 [get_ports  "SW[0]" ];
set_property PACKAGE_PIN B9 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[1]}]
set_property PACKAGE_PIN G11 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[2]}]
set_property PACKAGE_PIN F10 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SW[3]}]



#set_property PACKAGE_PIN E10 [get_ports TRIG_IN]
#set_property IOSTANDARD LVCMOS25 [get_ports TRIG_IN]
set_property PACKAGE_PIN D10 [get_ports TRIG_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports TRIG_OUT]
##################################
# FMC

#set_property PACKAGE_PIN U19 [get_ports {CLK_OUT[0]}]
#set_property IOSTANDARD LVDS_25 [get_ports {CLK_OUT[0]}]

#set_property PACKAGE_PIN AD21 [get_ports {CLK_OUT[1]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {CLK_OUT[1]}]

#set_property PACKAGE_PIN R18 [get_ports {CLK_OUT[2]}]
#set_property IOSTANDARD LVDS_25 [get_ports {CLK_OUT[2]}]

#set_property PACKAGE_PIN P18 [get_ports {CLK_OUT[3]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {CLK_OUT[3]}]

#set_property PACKAGE_PIN M24 [get_ports {FPGA_OUT[0]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {FPGA_OUT[0]}]

#set_property PACKAGE_PIN AD21 [get_ports {FPGA_OUT[1]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {FPGA_OUT[1]}]

#set_property PACKAGE_PIN AE21 [get_ports {FPGA_OUT[2]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {FPGA_OUT[2]}]

#set_property PACKAGE_PIN L24 [get_ports {FPGA_OUT[3]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {FPGA_OUT[3]}]


##################################
# FMC
set_property PACKAGE_PIN AA24 [get_ports {LA_N[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[0]}]
set_property PACKAGE_PIN AA23 [get_ports {LA_P[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[1]}]
set_property PACKAGE_PIN AB24 [get_ports {LA_N[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[1]}]
set_property PACKAGE_PIN AD21 [get_ports {LA_P[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[2]}]
set_property PACKAGE_PIN AE21 [get_ports {LA_N[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[2]}]
set_property PACKAGE_PIN AE23 [get_ports {LA_P[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[3]}]
set_property PACKAGE_PIN AF23 [get_ports {LA_N[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[3]}]
set_property PACKAGE_PIN AD25 [get_ports {LA_P[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[4]}]
set_property PACKAGE_PIN AE25 [get_ports {LA_N[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[4]}]
set_property PACKAGE_PIN AF24 [get_ports {LA_P[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[5]}]
set_property PACKAGE_PIN AF25 [get_ports {LA_N[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[5]}]
set_property PACKAGE_PIN AE22 [get_ports {LA_P[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[6]}]
set_property PACKAGE_PIN AF22 [get_ports {LA_N[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[6]}]
set_property PACKAGE_PIN AB21 [get_ports {LA_P[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[7]}]
set_property PACKAGE_PIN AC21 [get_ports {LA_N[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[7]}]
set_property PACKAGE_PIN AD26 [get_ports {LA_P[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[8]}]
set_property PACKAGE_PIN AE26 [get_ports {LA_N[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[8]}]
set_property PACKAGE_PIN AB22 [get_ports {LA_P[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[9]}]
set_property PACKAGE_PIN AC22 [get_ports {LA_N[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[9]}]
set_property PACKAGE_PIN W20 [get_ports {LA_P[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[10]}]
set_property PACKAGE_PIN Y21 [get_ports {LA_N[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[10]}]
set_property PACKAGE_PIN AD23 [get_ports {LA_P[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[11]}]
set_property PACKAGE_PIN AD24 [get_ports {LA_N[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[11]}]
set_property PACKAGE_PIN V21 [get_ports {LA_P[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[12]}]
set_property PACKAGE_PIN W21 [get_ports {LA_N[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[12]}]
set_property PACKAGE_PIN AA25 [get_ports {LA_P[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[13]}]
set_property PACKAGE_PIN AB25 [get_ports {LA_N[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[13]}]
set_property PACKAGE_PIN Y25 [get_ports {LA_P[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[14]}]
set_property PACKAGE_PIN Y26 [get_ports {LA_N[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[14]}]
set_property PACKAGE_PIN AB26 [get_ports {LA_P[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[15]}]
set_property PACKAGE_PIN AC26 [get_ports {LA_N[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[15]}]
set_property PACKAGE_PIN W23 [get_ports {LA_P[16]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[16]}]
set_property PACKAGE_PIN W24 [get_ports {LA_N[16]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[16]}]

set_property PACKAGE_PIN N21 [get_ports {LA_P[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[17]}]
set_property PACKAGE_PIN N22 [get_ports {LA_N[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[17]}]
set_property PACKAGE_PIN P23 [get_ports {LA_P[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[18]}]
set_property PACKAGE_PIN N23 [get_ports {LA_N[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[18]}]
set_property PACKAGE_PIN R18 [get_ports {LA_P[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[19]}]
#set_property IOSTANDARD LVDS_25 [get_ports {LA_P[19]}]
set_property PACKAGE_PIN P18 [get_ports {LA_N[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[19]}]
set_property PACKAGE_PIN U17 [get_ports {LA_P[20]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[20]}]
set_property PACKAGE_PIN T17 [get_ports {LA_N[20]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[20]}]
set_property PACKAGE_PIN R16 [get_ports {LA_P[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[21]}]
set_property PACKAGE_PIN R17 [get_ports {LA_N[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[21]}]
set_property PACKAGE_PIN P16 [get_ports {LA_P[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[22]}]
set_property PACKAGE_PIN N17 [get_ports {LA_N[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[22]}]
set_property PACKAGE_PIN N18 [get_ports {LA_P[23]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[23]}]
set_property PACKAGE_PIN M19 [get_ports {LA_N[23]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[23]}]
set_property PACKAGE_PIN U19 [get_ports {LA_P[24]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[24]}]
#set_property IOSTANDARD LVDS_25 [get_ports {LA_P[24]}]
set_property PACKAGE_PIN U20 [get_ports {LA_N[24]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[24]}]
set_property PACKAGE_PIN T18 [get_ports {LA_P[25]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[25]}]
set_property PACKAGE_PIN T19 [get_ports {LA_N[25]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[25]}]
set_property PACKAGE_PIN T24 [get_ports {LA_P[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[26]}]
set_property PACKAGE_PIN T25 [get_ports {LA_N[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[26]}]
set_property PACKAGE_PIN T22 [get_ports {LA_P[27]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[27]}]
set_property PACKAGE_PIN T23 [get_ports {LA_N[27]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[27]}]
set_property PACKAGE_PIN T20 [get_ports {LA_P[28]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[28]}]
set_property PACKAGE_PIN R20 [get_ports {LA_N[28]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[28]}]
set_property PACKAGE_PIN R22 [get_ports {LA_P[29]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[29]}]
set_property PACKAGE_PIN R23 [get_ports {LA_N[29]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[29]}]
set_property PACKAGE_PIN M21 [get_ports {LA_P[30]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[30]}]
set_property PACKAGE_PIN M22 [get_ports {LA_N[30]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[30]}]
set_property PACKAGE_PIN P19 [get_ports {LA_P[31]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[31]}]
set_property PACKAGE_PIN P20 [get_ports {LA_N[31]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[31]}]
set_property PACKAGE_PIN M24 [get_ports {LA_P[32]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[32]}]
set_property PACKAGE_PIN L24 [get_ports {LA_N[32]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[32]}]
set_property PACKAGE_PIN N19 [get_ports {LA_P[33]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_P[33]}]
set_property PACKAGE_PIN M20 [get_ports {LA_N[33]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LA_N[33]}]


set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property PULLDOWN true [get_ports {FPGA_OUT[0]}]
set_property PULLDOWN true [get_ports {FPGA_OUT[1]}]


set_property DRIVE 12 [get_ports {FPGA_OUT[0]}]
set_property DRIVE 12 [get_ports {FPGA_OUT[1]}]
set_property DRIVE 12 [get_ports {CLK_OUT[0]}]
set_property DRIVE 12 [get_ports {CLK_OUT[1]}]

set_max_delay -from [get_pins SiTCP_rfd_top/RBCP_REG/TDC_RST_ON_reg/C] -to [get_pins TDC_RST_reg/D] 4.0
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk125]
