#Local CLK
set_property PACKAGE_PIN G13 [get_ports EXT_CLK] 
set_property IOSTANDARD LVCMOS33 [get_ports EXT_CLK]
create_clock -period 8.000 -name EXT_CLK [get_ports EXT_CLK]

# set_property PACKAGE_PIN J12 [get_ports synclock] 
# set_property IOSTANDARD LVCMOS33 [get_ports synclock]


# 1. 锁定 TCK 输出，防止时钟抖动
# INST "TCK[1]" IOB = TRUE;

# # 2. 锁定 TMS 和 TDI 输出
# INST "uut/tms" IOB = TRUE;
# INST "uut/tdi" IOB = TRUE;

# 3. 锁定 TDO 的第一个采样寄存器 (这是解决延迟波动的关键)
# 注意：在代码中，tdo 被直接写进了 tdo_buffer。
# 建议在代码中先用一个 reg 抓一下 tdo，然后约束这个 reg。
#NET "tdo" IOB = TRUE;

### LVDS
set_property PACKAGE_PIN AE30 [get_ports CLK_LVDS25_P[1]] 
# pin reverse
set_property PACKAGE_PIN AF22 [get_ports CLK_LVDS25_P[2]] 
# pin reverse
set_property PACKAGE_PIN AH26 [get_ports CLK_LVDS25_P[3]] 
# pin reverse
set_property PACKAGE_PIN AB22 [get_ports CLK_LVDS25_P[4]] 
# pin reverse
set_property PACKAGE_PIN Y23  [get_ports CLK_LVDS25_P[5]] 
set_property PACKAGE_PIN F20  [get_ports CLK_LVDS25_P[6]] 
set_property PACKAGE_PIN Y26  [get_ports CLK_LVDS25_P[7]] 
set_property PACKAGE_PIN K19  [get_ports CLK_LVDS25_P[8]] 
set_property PACKAGE_PIN B30  [get_ports CLK_LVDS25_P[9]] 
set_property PACKAGE_PIN A16  [get_ports CLK_LVDS25_P[10]] 

# # pin reverse
set_property PACKAGE_PIN C24  [get_ports CLK_LVDS25_P[11]] 
set_property PACKAGE_PIN D16  [get_ports CLK_LVDS25_P[12]] 

# pin reverse
set_property PACKAGE_PIN AK29 [get_ports DATA_LVDS25_P[1]] 
# pin reverse
set_property PACKAGE_PIN AF20 [get_ports DATA_LVDS25_P[2]] 
# pin reverse
set_property PACKAGE_PIN AG25 [get_ports DATA_LVDS25_P[3]] 
set_property PACKAGE_PIN Y21  [get_ports DATA_LVDS25_P[4]] 
# pin reverse
set_property PACKAGE_PIN AA27 [get_ports DATA_LVDS25_P[5]] 
set_property PACKAGE_PIN G22  [get_ports DATA_LVDS25_P[6]] 
set_property PACKAGE_PIN W29  [get_ports DATA_LVDS25_P[7]] 
set_property PACKAGE_PIN G23  [get_ports DATA_LVDS25_P[8]] 
set_property PACKAGE_PIN E29  [get_ports DATA_LVDS25_P[9]] 
set_property PACKAGE_PIN A20  [get_ports DATA_LVDS25_P[10]] 
# pin reverse
set_property PACKAGE_PIN D26  [get_ports DATA_LVDS25_P[11]] 
set_property PACKAGE_PIN D17  [get_ports DATA_LVDS25_P[12]] 

# pin reverse
set_property PACKAGE_PIN AJ27 [get_ports FB_LVDS25_P[1]] 
# pin reverse
set_property PACKAGE_PIN AA20 [get_ports FB_LVDS25_P[2]] 
# pin reverse
set_property PACKAGE_PIN AG24 [get_ports FB_LVDS25_P[3]] 
set_property PACKAGE_PIN AC20 [get_ports FB_LVDS25_P[4]] 
set_property PACKAGE_PIN AD29 [get_ports FB_LVDS25_P[5]] 
# pin reverse
set_property PACKAGE_PIN E24  [get_ports FB_LVDS25_P[6]] 
# pin reverse
set_property PACKAGE_PIN Y28  [get_ports FB_LVDS25_P[7]] 
set_property PACKAGE_PIN H24  [get_ports FB_LVDS25_P[8]] 
# pin reverse
set_property PACKAGE_PIN G29  [get_ports FB_LVDS25_P[9]] 
set_property PACKAGE_PIN B22  [get_ports FB_LVDS25_P[10]] 
# pin reverse
set_property PACKAGE_PIN D27  [get_ports FB_LVDS25_P[11]] 
# pin reverse
set_property PACKAGE_PIN C19  [get_ports FB_LVDS25_P[12]] 

set_property PACKAGE_PIN AG30 [get_ports RESET_LVDS25_P[1]] 
set_property PACKAGE_PIN AD21 [get_ports RESET_LVDS25_P[2]] 
set_property PACKAGE_PIN AE25 [get_ports RESET_LVDS25_P[3]] 
set_property PACKAGE_PIN AC22 [get_ports RESET_LVDS25_P[4]] 
# pin reverse
set_property PACKAGE_PIN AA22 [get_ports RESET_LVDS25_P[5]] 
set_property PACKAGE_PIN F21  [get_ports RESET_LVDS25_P[6]] 
set_property PACKAGE_PIN W27  [get_ports RESET_LVDS25_P[7]] 
set_property PACKAGE_PIN H21  [get_ports RESET_LVDS25_P[8]] 
# pin reverse
set_property PACKAGE_PIN D29  [get_ports RESET_LVDS25_P[9]] 
set_property PACKAGE_PIN B18  [get_ports RESET_LVDS25_P[10]] 
# pin reverse
set_property PACKAGE_PIN C25  [get_ports RESET_LVDS25_P[11]] 
set_property PACKAGE_PIN C17  [get_ports RESET_LVDS25_P[12]] 

# pin reverse
set_property PACKAGE_PIN AK23 [get_ports FTMS_LVDS25_P[1]]
# pin reverse
set_property PACKAGE_PIN AB29 [get_ports FTMS_LVDS25_P[2]]
# pin reverse
set_property PACKAGE_PIN AH21 [get_ports FTMS_LVDS25_P[3]]
# pin reverse
set_property PACKAGE_PIN AG27 [get_ports FTMS_LVDS25_P[4]]
set_property PACKAGE_PIN AD23 [get_ports FTMS_LVDS25_P[5]]
# pin reverse
set_property PACKAGE_PIN G28  [get_ports FTMS_LVDS25_P[6]]
# pin reverse
set_property PACKAGE_PIN AB27 [get_ports FTMS_LVDS25_P[7]]
# pin reverse
set_property PACKAGE_PIN G27  [get_ports FTMS_LVDS25_P[8]]
set_property PACKAGE_PIN L17  [get_ports FTMS_LVDS25_P[9]]
set_property PACKAGE_PIN B27  [get_ports FTMS_LVDS25_P[10]]
set_property PACKAGE_PIN J19  [get_ports FTMS_LVDS25_P[11]]
# pin reverse
set_property PACKAGE_PIN D22  [get_ports FTMS_LVDS25_P[12]]
# pin reverse
set_property PACKAGE_PIN AJ26 [get_ports FTCK_LVDS25_P[1]]
# pin reverse
set_property PACKAGE_PIN AE28 [get_ports FTCK_LVDS25_P[2]]
# pin reverse
set_property PACKAGE_PIN AJ22 [get_ports FTCK_LVDS25_P[3]]
set_property PACKAGE_PIN AG29 [get_ports FTCK_LVDS25_P[4]]
set_property PACKAGE_PIN AA25 [get_ports FTCK_LVDS25_P[5]]
# pin reverse
set_property PACKAGE_PIN C29  [get_ports FTCK_LVDS25_P[6]]
set_property PACKAGE_PIN AC26 [get_ports FTCK_LVDS25_P[7]]
# pin reverse
set_property PACKAGE_PIN E28  [get_ports FTCK_LVDS25_P[8]]
set_property PACKAGE_PIN G17  [get_ports FTCK_LVDS25_P[9]]
set_property PACKAGE_PIN B23  [get_ports FTCK_LVDS25_P[10]]
set_property PACKAGE_PIN J17  [get_ports FTCK_LVDS25_P[11]]
set_property PACKAGE_PIN C20  [get_ports FTCK_LVDS25_P[12]]
# pin reverse
set_property PACKAGE_PIN AJ24 [get_ports FTDI_LVDS25_P[1]]
set_property PACKAGE_PIN Y30  [get_ports FTDI_LVDS25_P[2]]
# pin reverse
set_property PACKAGE_PIN AG22 [get_ports FTDI_LVDS25_P[3]]
# pin reverse
set_property PACKAGE_PIN AJ28 [get_ports FTDI_LVDS25_P[4]]
set_property PACKAGE_PIN AB24 [get_ports FTDI_LVDS25_P[5]]
# pin reverse
set_property PACKAGE_PIN F26  [get_ports FTDI_LVDS25_P[6]]
# pin reverse
set_property PACKAGE_PIN AD27 [get_ports FTDI_LVDS25_P[7]]
# pin reverse
set_property PACKAGE_PIN F25  [get_ports FTDI_LVDS25_P[8]]
set_property PACKAGE_PIN G18  [get_ports FTDI_LVDS25_P[9]]
set_property PACKAGE_PIN A25  [get_ports FTDI_LVDS25_P[10]]
set_property PACKAGE_PIN K18  [get_ports FTDI_LVDS25_P[11]]
# pin reverse
set_property PACKAGE_PIN D21  [get_ports FTDI_LVDS25_P[12]]
# pin reverse
set_property PACKAGE_PIN AK20 [get_ports FTDO_LVDS25_P[1]] 
# pin reverse
set_property PACKAGE_PIN AC29 [get_ports FTDO_LVDS25_P[2]] 
# pin reverse
set_property PACKAGE_PIN AG20 [get_ports FTDO_LVDS25_P[3]] 
# pin reverse
set_property PACKAGE_PIN AF26 [get_ports FTDO_LVDS25_P[4]] 
# pin reverse
set_property PACKAGE_PIN AE23 [get_ports FTDO_LVDS25_P[5]] 
# pin reverse
set_property PACKAGE_PIN H30  [get_ports FTDO_LVDS25_P[6]] 
set_property PACKAGE_PIN AC24 [get_ports FTDO_LVDS25_P[7]] 
set_property PACKAGE_PIN H26  [get_ports FTDO_LVDS25_P[8]] 
set_property PACKAGE_PIN E19  [get_ports FTDO_LVDS25_P[9]] 
set_property PACKAGE_PIN B28  [get_ports FTDO_LVDS25_P[10]] 
set_property PACKAGE_PIN H20  [get_ports FTDO_LVDS25_P[11]] 
# pin reverse
set_property PACKAGE_PIN E23  [get_ports FTDO_LVDS25_P[12]] 



# # pin reverse
# set_property PACKAGE_PIN AE30 [get_ports CLK_LVDS25_P[1]] 
# set_property PACKAGE_PIN AF30 [get_ports CLK_LVDS25_N[1]] 
# # pin reverse
# set_property PACKAGE_PIN AG23 [get_ports CLK_LVDS25_P[2]] 
# set_property PACKAGE_PIN AF22 [get_ports CLK_LVDS25_N[2]] 
# # pin reverse
# set_property PACKAGE_PIN AH27 [get_ports CLK_LVDS25_P[3]] 
# set_property PACKAGE_PIN AH26 [get_ports CLK_LVDS25_N[3]] 
# # pin reverse
# set_property PACKAGE_PIN AB23 [get_ports CLK_LVDS25_P[4]] 
# set_property PACKAGE_PIN AB22 [get_ports CLK_LVDS25_N[4]] 
# # pin reverse
# set_property PACKAGE_PIN Y24  [get_ports CLK_LVDS25_P[5]] 
# set_property PACKAGE_PIN Y23  [get_ports CLK_LVDS25_N[5]] 
# set_property PACKAGE_PIN F20  [get_ports CLK_LVDS25_P[6]] 
# set_property PACKAGE_PIN E20  [get_ports CLK_LVDS25_N[6]] 
# set_property PACKAGE_PIN Y26  [get_ports CLK_LVDS25_P[7]] 
# set_property PACKAGE_PIN AA26 [get_ports CLK_LVDS25_N[7]] 
# set_property PACKAGE_PIN K19  [get_ports CLK_LVDS25_P[8]] 
# set_property PACKAGE_PIN K20  [get_ports CLK_LVDS25_N[8]] 
# set_property PACKAGE_PIN B30  [get_ports CLK_LVDS25_P[9]] 
# set_property PACKAGE_PIN A30  [get_ports CLK_LVDS25_N[9]] 
# set_property PACKAGE_PIN A16  [get_ports CLK_LVDS25_P[10]] 
# set_property PACKAGE_PIN A17  [get_ports CLK_LVDS25_N[10]] 
# # # pin reverse
# set_property PACKAGE_PIN B24  [get_ports CLK_LVDS25_P[11]] 
# set_property PACKAGE_PIN C24  [get_ports CLK_LVDS25_N[11]] 
# set_property PACKAGE_PIN D16  [get_ports CLK_LVDS25_P[12]] 
# set_property PACKAGE_PIN C16  [get_ports CLK_LVDS25_N[12]] 
# # pin reverse
# set_property PACKAGE_PIN AK30 [get_ports DATA_LVDS25_P[1]] 
# set_property PACKAGE_PIN AK29 [get_ports DATA_LVDS25_N[1]] 
# # pin reverse
# set_property PACKAGE_PIN AF20 [get_ports DATA_LVDS25_P[2]] 
# # pin reverse
# set_property PACKAGE_PIN AG25 [get_ports DATA_LVDS25_P[3]] 
# set_property PACKAGE_PIN Y21  [get_ports DATA_LVDS25_P[4]] 
# set_property PACKAGE_PIN AA21 [get_ports DATA_LVDS25_N[4]] 
# # pin reverse
# set_property PACKAGE_PIN AB28 [get_ports DATA_LVDS25_P[5]] 
# set_property PACKAGE_PIN AA27 [get_ports DATA_LVDS25_N[5]] 
# set_property PACKAGE_PIN G22  [get_ports DATA_LVDS25_P[6]] 
# set_property PACKAGE_PIN F22  [get_ports DATA_LVDS25_N[6]] 
# set_property PACKAGE_PIN W29  [get_ports DATA_LVDS25_P[7]] 
# set_property PACKAGE_PIN Y29  [get_ports DATA_LVDS25_N[7]] 
# set_property PACKAGE_PIN G23  [get_ports DATA_LVDS25_P[8]] 
# set_property PACKAGE_PIN G24  [get_ports DATA_LVDS25_N[8]] 
# set_property PACKAGE_PIN E29  [get_ports DATA_LVDS25_P[9]] 
# set_property PACKAGE_PIN E30  [get_ports DATA_LVDS25_N[9]] 
# set_property PACKAGE_PIN A20  [get_ports DATA_LVDS25_P[10]] 
# # pin reverse
# set_property PACKAGE_PIN C26  [get_ports DATA_LVDS25_P[11]] 
# set_property PACKAGE_PIN D26  [get_ports DATA_LVDS25_N[11]] 
# set_property PACKAGE_PIN D17  [get_ports DATA_LVDS25_P[12]] 
# set_property PACKAGE_PIN D18  [get_ports DATA_LVDS25_N[12]] 
# # pin reverse
# set_property PACKAGE_PIN AK28 [get_ports FB_LVDS25_P[1]] 
# set_property PACKAGE_PIN AJ27 [get_ports FB_LVDS25_N[1]] 
# # pin reverse
# set_property PACKAGE_PIN AB20 [get_ports FB_LVDS25_P[2]] 
# set_property PACKAGE_PIN AA20 [get_ports FB_LVDS25_N[2]] 
# # pin reverse
# set_property PACKAGE_PIN AH24 [get_ports FB_LVDS25_P[3]] 
# set_property PACKAGE_PIN AG24 [get_ports FB_LVDS25_N[3]] 
# set_property PACKAGE_PIN AC20 [get_ports FB_LVDS25_P[4]] 
# set_property PACKAGE_PIN AC21 [get_ports FB_LVDS25_N[4]] 
# set_property PACKAGE_PIN AD29 [get_ports FB_LVDS25_P[5]] 
# set_property PACKAGE_PIN AE29 [get_ports FB_LVDS25_N[5]] 
# # pin reverse
# set_property PACKAGE_PIN D24  [get_ports FB_LVDS25_P[6]] 
# set_property PACKAGE_PIN E24  [get_ports FB_LVDS25_N[6]] 
# # pin reverse
# set_property PACKAGE_PIN Y28  [get_ports FB_LVDS25_P[7]] 
# set_property PACKAGE_PIN AA28 [get_ports FB_LVDS25_N[7]] 
# set_property PACKAGE_PIN H24  [get_ports FB_LVDS25_P[8]] 
# set_property PACKAGE_PIN H25  [get_ports FB_LVDS25_N[8]] 
# # pin reverse
# set_property PACKAGE_PIN F30  [get_ports FB_LVDS25_P[9]] 
# set_property PACKAGE_PIN G29  [get_ports FB_LVDS25_N[9]] 
# set_property PACKAGE_PIN B22  [get_ports FB_LVDS25_P[10]] 
# set_property PACKAGE_PIN A22  [get_ports FB_LVDS25_N[10]] 
# # pin reverse
# set_property PACKAGE_PIN C27  [get_ports FB_LVDS25_P[11]] 
# set_property PACKAGE_PIN D27  [get_ports FB_LVDS25_N[11]] 
# # pin reverse
# set_property PACKAGE_PIN B19  [get_ports FB_LVDS25_P[12]] 
# set_property PACKAGE_PIN C19  [get_ports FB_LVDS25_N[12]] 

# set_property PACKAGE_PIN AG30 [get_ports RESET_LVDS25_P[1]] 
# set_property PACKAGE_PIN AH30 [get_ports RESET_LVDS25_N[1]] 
# set_property PACKAGE_PIN AD21 [get_ports RESET_LVDS25_P[2]] 
# set_property PACKAGE_PIN AE21 [get_ports RESET_LVDS25_N[2]] 
# set_property PACKAGE_PIN AE25 [get_ports RESET_LVDS25_P[3]] 
# set_property PACKAGE_PIN AF25 [get_ports RESET_LVDS25_N[3]] 
# set_property PACKAGE_PIN AC22 [get_ports RESET_LVDS25_P[4]] 
# set_property PACKAGE_PIN AD22 [get_ports RESET_LVDS25_N[4]] 
# # pin reverse
# set_property PACKAGE_PIN AA23 [get_ports RESET_LVDS25_P[5]] 
# set_property PACKAGE_PIN AA22 [get_ports RESET_LVDS25_N[5]] 
# set_property PACKAGE_PIN F21  [get_ports RESET_LVDS25_P[6]] 
# set_property PACKAGE_PIN E21  [get_ports RESET_LVDS25_N[6]] 
# set_property PACKAGE_PIN W27  [get_ports RESET_LVDS25_P[7]] 
# set_property PACKAGE_PIN W28  [get_ports RESET_LVDS25_N[7]] 
# set_property PACKAGE_PIN H21  [get_ports RESET_LVDS25_P[8]] 
# set_property PACKAGE_PIN H22  [get_ports RESET_LVDS25_N[8]] 
# # pin reverse
# set_property PACKAGE_PIN C30  [get_ports RESET_LVDS25_P[9]] 
# set_property PACKAGE_PIN D29  [get_ports RESET_LVDS25_N[9]] 
# set_property PACKAGE_PIN B18  [get_ports RESET_LVDS25_P[10]] 
# set_property PACKAGE_PIN A18  [get_ports RESET_LVDS25_N[10]] 
# # pin reverse
# set_property PACKAGE_PIN B25  [get_ports RESET_LVDS25_P[11]] 
# set_property PACKAGE_PIN C25  [get_ports RESET_LVDS25_N[11]] 
# set_property PACKAGE_PIN C17  [get_ports RESET_LVDS25_P[12]] 
# set_property PACKAGE_PIN B17  [get_ports RESET_LVDS25_N[12]] 
# # pin reverse
# set_property PACKAGE_PIN AK23 [get_ports FTMS_LVDS25_P[1]]
# # pin reverse
# set_property PACKAGE_PIN AB30 [get_ports FTMS_LVDS25_P[2]]
# set_property PACKAGE_PIN AB29 [get_ports FTMS_LVDS25_N[2]]
# # pin reverse
# set_property PACKAGE_PIN AJ21 [get_ports FTMS_LVDS25_P[3]]
# set_property PACKAGE_PIN AH21 [get_ports FTMS_LVDS25_N[3]]
# # pin reverse
# set_property PACKAGE_PIN AG28 [get_ports FTMS_LVDS25_P[4]]
# set_property PACKAGE_PIN AG27 [get_ports FTMS_LVDS25_N[4]]
# set_property PACKAGE_PIN AE24 [get_ports FTMS_LVDS25_P[5]]
# set_property PACKAGE_PIN AD23 [get_ports FTMS_LVDS25_N[5]]
# # pin reverse
# set_property PACKAGE_PIN F28  [get_ports FTMS_LVDS25_P[6]]
# set_property PACKAGE_PIN G28  [get_ports FTMS_LVDS25_N[6]]
# # pin reverse
# set_property PACKAGE_PIN AC27 [get_ports FTMS_LVDS25_P[7]]
# set_property PACKAGE_PIN AB27 [get_ports FTMS_LVDS25_N[7]]
# # pin reverse
# set_property PACKAGE_PIN F27  [get_ports FTMS_LVDS25_P[8]]
# set_property PACKAGE_PIN G27  [get_ports FTMS_LVDS25_N[8]]
# set_property PACKAGE_PIN L17  [get_ports FTMS_LVDS25_P[9]]
# set_property PACKAGE_PIN L18  [get_ports FTMS_LVDS25_N[9]]
# set_property PACKAGE_PIN B27  [get_ports FTMS_LVDS25_P[10]]
# set_property PACKAGE_PIN A27  [get_ports FTMS_LVDS25_N[10]]
# set_property PACKAGE_PIN J19  [get_ports FTMS_LVDS25_P[11]]
# set_property PACKAGE_PIN H19  [get_ports FTMS_LVDS25_N[11]]
# # pin reverse
# set_property PACKAGE_PIN D22  [get_ports FTMS_LVDS25_P[12]]
# # pin reverse
# set_property PACKAGE_PIN AK26 [get_ports FTCK_LVDS25_P[1]]
# set_property PACKAGE_PIN AJ26 [get_ports FTCK_LVDS25_N[1]]
# # pin reverse
# set_property PACKAGE_PIN AF28 [get_ports FTCK_LVDS25_P[2]]
# set_property PACKAGE_PIN AE28 [get_ports FTCK_LVDS25_N[2]]
# # pin reverse
# set_property PACKAGE_PIN AJ23 [get_ports FTCK_LVDS25_P[3]]
# set_property PACKAGE_PIN AJ22 [get_ports FTCK_LVDS25_N[3]]
# set_property PACKAGE_PIN AG29 [get_ports FTCK_LVDS25_P[4]]
# set_property PACKAGE_PIN AH29 [get_ports FTCK_LVDS25_N[4]]
# set_property PACKAGE_PIN AA25 [get_ports FTCK_LVDS25_P[5]]
# set_property PACKAGE_PIN AB25 [get_ports FTCK_LVDS25_N[5]]
# # pin reverse
# set_property PACKAGE_PIN B29  [get_ports FTCK_LVDS25_P[6]]
# set_property PACKAGE_PIN C29  [get_ports FTCK_LVDS25_N[6]]
# set_property PACKAGE_PIN AC26 [get_ports FTCK_LVDS25_P[7]]
# set_property PACKAGE_PIN AD26 [get_ports FTCK_LVDS25_N[7]]
# # pin reverse
# set_property PACKAGE_PIN D28  [get_ports FTCK_LVDS25_P[8]]
# set_property PACKAGE_PIN E28  [get_ports FTCK_LVDS25_N[8]]
# set_property PACKAGE_PIN G17  [get_ports FTCK_LVDS25_P[9]]
# set_property PACKAGE_PIN F17  [get_ports FTCK_LVDS25_N[9]]
# set_property PACKAGE_PIN B23  [get_ports FTCK_LVDS25_P[10]]
# set_property PACKAGE_PIN A23  [get_ports FTCK_LVDS25_N[10]]
# set_property PACKAGE_PIN J17  [get_ports FTCK_LVDS25_P[11]]
# set_property PACKAGE_PIN H17  [get_ports FTCK_LVDS25_N[11]]
# set_property PACKAGE_PIN B20  [get_ports FTCK_LVDS25_P[12]]
# set_property PACKAGE_PIN C20  [get_ports FTCK_LVDS25_N[12]]
# # pin reverse
# set_property PACKAGE_PIN AJ24 [get_ports FTDI_LVDS25_P[1]]
# set_property PACKAGE_PIN Y30  [get_ports FTDI_LVDS25_P[2]]
# set_property PACKAGE_PIN AA30 [get_ports FTDI_LVDS25_N[2]]
# # pin reverse
# set_property PACKAGE_PIN AH22 [get_ports FTDI_LVDS25_P[3]]
# set_property PACKAGE_PIN AG22 [get_ports FTDI_LVDS25_N[3]]
# # pin reverse
# set_property PACKAGE_PIN AJ29 [get_ports FTDI_LVDS25_P[4]]
# set_property PACKAGE_PIN AJ28 [get_ports FTDI_LVDS25_N[4]]
# set_property PACKAGE_PIN AB24 [get_ports FTDI_LVDS25_P[5]]
# set_property PACKAGE_PIN AC25 [get_ports FTDI_LVDS25_N[5]]
# # pin reverse
# set_property PACKAGE_PIN E26  [get_ports FTDI_LVDS25_P[6]]
# set_property PACKAGE_PIN F26  [get_ports FTDI_LVDS25_N[6]]
# # pin reverse
# set_property PACKAGE_PIN AD28 [get_ports FTDI_LVDS25_P[7]]
# set_property PACKAGE_PIN AD27 [get_ports FTDI_LVDS25_N[7]]
# # pin reverse
# set_property PACKAGE_PIN E25  [get_ports FTDI_LVDS25_P[8]]
# set_property PACKAGE_PIN F25  [get_ports FTDI_LVDS25_N[8]]
# set_property PACKAGE_PIN G18  [get_ports FTDI_LVDS25_P[9]]
# set_property PACKAGE_PIN F18  [get_ports FTDI_LVDS25_N[9]]
# set_property PACKAGE_PIN A25  [get_ports FTDI_LVDS25_P[10]]
# set_property PACKAGE_PIN K18  [get_ports FTDI_LVDS25_P[11]]
# set_property PACKAGE_PIN J18  [get_ports FTDI_LVDS25_N[11]]
# # pin reverse
# set_property PACKAGE_PIN C21  [get_ports FTDI_LVDS25_P[12]]
# set_property PACKAGE_PIN D21  [get_ports FTDI_LVDS25_N[12]]
# # pin reverse
# set_property PACKAGE_PIN AK21 [get_ports FTDO_LVDS25_P[1]] 
# set_property PACKAGE_PIN AK20 [get_ports FTDO_LVDS25_N[1]] 
# # pin reverse
# set_property PACKAGE_PIN AC30 [get_ports FTDO_LVDS25_P[2]] 
# set_property PACKAGE_PIN AC29 [get_ports FTDO_LVDS25_N[2]] 

# # pin reverse
# set_property PACKAGE_PIN AH20 [get_ports FTDO_LVDS25_P[3]] 
# set_property PACKAGE_PIN AG20 [get_ports FTDO_LVDS25_N[3]] 
# # pin reverse
# set_property PACKAGE_PIN AF27 [get_ports FTDO_LVDS25_P[4]] 
# set_property PACKAGE_PIN AF26 [get_ports FTDO_LVDS25_N[4]] 
# # pin reverse
# set_property PACKAGE_PIN AF23 [get_ports FTDO_LVDS25_P[5]] 
# set_property PACKAGE_PIN AE23 [get_ports FTDO_LVDS25_N[5]] 
# # pin reverse
# set_property PACKAGE_PIN G30  [get_ports FTDO_LVDS25_P[6]] 
# set_property PACKAGE_PIN H30  [get_ports FTDO_LVDS25_N[6]] 
# set_property PACKAGE_PIN AC24 [get_ports FTDO_LVDS25_P[7]] 
# set_property PACKAGE_PIN AD24 [get_ports FTDO_LVDS25_N[7]] 
# set_property PACKAGE_PIN H26  [get_ports FTDO_LVDS25_P[8]] 
# set_property PACKAGE_PIN H27  [get_ports FTDO_LVDS25_N[8]] 
# set_property PACKAGE_PIN E19  [get_ports FTDO_LVDS25_P[9]] 
# set_property PACKAGE_PIN D19  [get_ports FTDO_LVDS25_N[9]] 
# set_property PACKAGE_PIN B28  [get_ports FTDO_LVDS25_P[10]] 
# set_property PACKAGE_PIN A28  [get_ports FTDO_LVDS25_N[10]] 
# set_property PACKAGE_PIN H20  [get_ports FTDO_LVDS25_P[11]] 
# set_property PACKAGE_PIN G20  [get_ports FTDO_LVDS25_N[11]] 
# # pin reverse
# set_property PACKAGE_PIN D23  [get_ports FTDO_LVDS25_P[12]] 
# set_property PACKAGE_PIN E23  [get_ports FTDO_LVDS25_N[12]] 

set_property PACKAGE_PIN P26 [get_ports {TCK[1]}]
set_property PACKAGE_PIN P28 [get_ports {TCK[2]}]
set_property PACKAGE_PIN R24 [get_ports {TCK[3]}]
set_property PACKAGE_PIN V27 [get_ports {TCK[4]}]
set_property PACKAGE_PIN U30 [get_ports {TCK[5]}]
set_property PACKAGE_PIN M30 [get_ports {TCK[6]}]
set_property PACKAGE_PIN R29 [get_ports {TCK[7]}]
set_property PACKAGE_PIN K29 [get_ports {TCK[8]}]
set_property PACKAGE_PIN J27 [get_ports {TCK[9]}]
set_property PACKAGE_PIN N26 [get_ports {TCK[10]}]
set_property PACKAGE_PIN M28 [get_ports {TCK[11]}]
set_property PACKAGE_PIN M24 [get_ports {TCK[12]}]

set_property PACKAGE_PIN V25 [get_ports {TMS[1]}]
set_property PACKAGE_PIN U27 [get_ports {TMS[2]}]
set_property PACKAGE_PIN R26 [get_ports {TMS[3]}]
set_property PACKAGE_PIN R28 [get_ports {TMS[4]}]
set_property PACKAGE_PIN T30 [get_ports {TMS[5]}]
set_property PACKAGE_PIN L30 [get_ports {TMS[6]}]
set_property PACKAGE_PIN U29 [get_ports {TMS[7]}]
set_property PACKAGE_PIN M29 [get_ports {TMS[8]}]
set_property PACKAGE_PIN L28 [get_ports {TMS[9]}]
set_property PACKAGE_PIN L26 [get_ports {TMS[10]}]
set_property PACKAGE_PIN L27 [get_ports {TMS[11]}]
set_property PACKAGE_PIN L25 [get_ports {TMS[12]}]

set_property PACKAGE_PIN T25 [get_ports {TDI[1]}]
set_property PACKAGE_PIN P27 [get_ports {TDI[2]}]
set_property PACKAGE_PIN V26 [get_ports {TDI[3]}]
set_property PACKAGE_PIN U28 [get_ports {TDI[4]}]
set_property PACKAGE_PIN R30 [get_ports {TDI[5]}]
set_property PACKAGE_PIN K30 [get_ports {TDI[6]}]
set_property PACKAGE_PIN V29 [get_ports {TDI[7]}]
set_property PACKAGE_PIN N29 [get_ports {TDI[8]}]
set_property PACKAGE_PIN J28 [get_ports {TDI[9]}]
set_property PACKAGE_PIN J26 [get_ports {TDI[10]}]
set_property PACKAGE_PIN N27 [get_ports {TDI[11]}]
set_property PACKAGE_PIN N25 [get_ports {TDI[12]}]

set_property PACKAGE_PIN T26 [get_ports {TDO[1]}]
set_property PACKAGE_PIN T28 [get_ports {TDO[2]}]
set_property PACKAGE_PIN U25 [get_ports {TDO[3]}]
set_property PACKAGE_PIN T27 [get_ports {TDO[4]}]
set_property PACKAGE_PIN V30 [get_ports {TDO[5]}]
set_property PACKAGE_PIN N30 [get_ports {TDO[6]}]
set_property PACKAGE_PIN P29 [get_ports {TDO[7]}]
set_property PACKAGE_PIN J29 [get_ports {TDO[8]}]
set_property PACKAGE_PIN M27 [get_ports {TDO[9]}]
set_property PACKAGE_PIN M25 [get_ports {TDO[10]}]
set_property PACKAGE_PIN K28 [get_ports {TDO[11]}]
set_property PACKAGE_PIN K26 [get_ports {TDO[12]}]

set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports CLK_LVDS25_P[12]]

set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports DATA_LVDS25_P[12]]

set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports RESET_LVDS25_P[12]]

set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports FB_LVDS25_P[12]]

# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[1]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[2]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[3]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[4]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[5]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[6]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[7]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[8]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[9]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[10]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[11]]
# set_property IOSTANDARD TMDS_33 [get_ports CLK_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS25 [get_ports CLK_LVDS25_N[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports DATA_LVDS25_N[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports RESET_LVDS25_N[12]]

# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS25 [get_ports FB_LVDS25_N[12]]

set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports FTMS_LVDS25_P[12]]

set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports FTCK_LVDS25_P[12]]

set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports FTDI_LVDS25_P[12]]

set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[1]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[2]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[3]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[4]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[5]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[6]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[7]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[8]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[9]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[10]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[11]]
set_property IOSTANDARD LVDS_25 [get_ports FTDO_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_P[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTMS_LVDS25_N[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTCK_LVDS25_N[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDI_LVDS25_N[12]]

# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[1]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[8]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[9]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[10]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[11]]
# set_property IOSTANDARD LVCMOS33 [get_ports FTDO_LVDS25_N[12]]

set_property IOSTANDARD LVCMOS33 [get_ports {TCK[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TCK[12]}]

set_property IOSTANDARD LVCMOS33 [get_ports {TMS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TMS[12]}]

set_property IOSTANDARD LVCMOS33 [get_ports {TDI[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDI[12]}]

set_property IOSTANDARD LVCMOS33 [get_ports {TDO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TDO[12]}]

set_property PULLDOWN true [get_ports {TCK[1]}]
set_property PULLDOWN true [get_ports {TCK[2]}]
set_property PULLDOWN true [get_ports {TCK[3]}]
set_property PULLDOWN true [get_ports {TCK[4]}]
set_property PULLDOWN true [get_ports {TCK[5]}]
set_property PULLDOWN true [get_ports {TCK[6]}]
set_property PULLDOWN true [get_ports {TCK[7]}]
set_property PULLDOWN true [get_ports {TCK[8]}]
set_property PULLDOWN true [get_ports {TCK[9]}]
set_property PULLDOWN true [get_ports {TCK[10]}]
set_property PULLDOWN true [get_ports {TCK[11]}]
set_property PULLDOWN true [get_ports {TCK[12]}]

set_property PULLDOWN true [get_ports {TMS[1]}]
set_property PULLDOWN true [get_ports {TMS[2]}]
set_property PULLDOWN true [get_ports {TMS[3]}]
set_property PULLDOWN true [get_ports {TMS[4]}]
set_property PULLDOWN true [get_ports {TMS[5]}]
set_property PULLDOWN true [get_ports {TMS[6]}]
set_property PULLDOWN true [get_ports {TMS[7]}]
set_property PULLDOWN true [get_ports {TMS[8]}]
set_property PULLDOWN true [get_ports {TMS[9]}]
set_property PULLDOWN true [get_ports {TMS[10]}]
set_property PULLDOWN true [get_ports {TMS[11]}]
set_property PULLDOWN true [get_ports {TMS[12]}]

set_property PULLDOWN true [get_ports {TDI[1]}]
set_property PULLDOWN true [get_ports {TDI[2]}]
set_property PULLDOWN true [get_ports {TDI[3]}]
set_property PULLDOWN true [get_ports {TDI[4]}]
set_property PULLDOWN true [get_ports {TDI[5]}]
set_property PULLDOWN true [get_ports {TDI[6]}]
set_property PULLDOWN true [get_ports {TDI[7]}]
set_property PULLDOWN true [get_ports {TDI[8]}]
set_property PULLDOWN true [get_ports {TDI[9]}]
set_property PULLDOWN true [get_ports {TDI[10]}]
set_property PULLDOWN true [get_ports {TDI[11]}]
set_property PULLDOWN true [get_ports {TDI[12]}]

set_property PULLDOWN true [get_ports {TDO[1]}]
set_property PULLDOWN true [get_ports {TDO[2]}]
set_property PULLDOWN true [get_ports {TDO[3]}]
set_property PULLDOWN true [get_ports {TDO[4]}]
set_property PULLDOWN true [get_ports {TDO[5]}]
set_property PULLDOWN true [get_ports {TDO[6]}]
set_property PULLDOWN true [get_ports {TDO[7]}]
set_property PULLDOWN true [get_ports {TDO[8]}]
set_property PULLDOWN true [get_ports {TDO[9]}]
set_property PULLDOWN true [get_ports {TDO[10]}]
set_property PULLDOWN true [get_ports {TDO[11]}]
set_property PULLDOWN true [get_ports {TDO[12]}]

# RST
set_property PACKAGE_PIN AG7 [get_ports RST]
set_property IOSTANDARD LVCMOS18 [get_ports RST]
set_property PULLDOWN true [get_ports RST]
# LED
set_property PACKAGE_PIN AH12 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[1]}]
set_property PULLDOWN true [get_ports {LED[1]}]

set_property PACKAGE_PIN AJ2 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[2]}]
set_property PULLDOWN true [get_ports {LED[2]}]

set_property PACKAGE_PIN AF2 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[3]}]
set_property PULLDOWN true [get_ports {LED[3]}]

set_property PACKAGE_PIN AG2 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[4]}]
set_property PULLDOWN true [get_ports {LED[4]}]

set_property PACKAGE_PIN AC2 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[5]}]
set_property PULLDOWN true [get_ports {LED[5]}]

set_property PACKAGE_PIN AD2 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[6]}]
set_property PULLDOWN true [get_ports {LED[6]}]


# FLASH
set_property PACKAGE_PIN U19 [get_ports FLASH_CS_n]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_CS_n]
set_property PACKAGE_PIN R25 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
set_property PACKAGE_PIN P24 [get_ports MOSI]                      
set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property PACKAGE_PIN R20 [get_ports WRITE_PROTECT_n]                      
set_property IOSTANDARD LVCMOS33 [get_ports WRITE_PROTECT_n]
set_property PACKAGE_PIN R21 [get_ports HOLD_n]                      
set_property IOSTANDARD LVCMOS33 [get_ports HOLD_n]

set_false_path -from [get_clocks clk_125M] -to [get_clocks clk_out1_clk_wiz_tcp]
set_false_path -from [get_clocks clk_out1_clk_wiz_tcp] -to [get_clocks clk_125M]
set_false_path -from [get_clocks clk_125M] -to [get_clocks gtrefclk_div2_i]
set_false_path -from [get_clocks gtrefclk_div2_i] -to [get_clocks clk_125M]
set_false_path -from [get_clocks CLK_62M5_DMTD] -to [get_clocks gtrefclk_div2_i]
set_false_path -from [get_clocks gtrefclk_div2_i] -to [get_clocks CLK_62M5_DMTD]